/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e0e3e5",
        "surface-dim": "#dad9dd",
        "on-background": "#1a1c1e",
        "surface-variant": "#e3e2e6",
        "on-secondary-container": "#626567",
        "primary-container": "#1a365d",
        "on-tertiary-fixed": "#0b1c30",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#455f88",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#adc7f7",
        "inverse-surface": "#2f3033",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface": "#faf9fd",
        "on-secondary-fixed-variant": "#444749",
        "on-primary-fixed": "#001b3c",
        "secondary-fixed-dim": "#c4c7c9",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f0f4",
        "on-primary-container": "#86a0cd",
        "inverse-primary": "#adc7f7",
        "tertiary-fixed": "#d3e4fe",
        "secondary": "#5c5f61",
        "tertiary-container": "#27374b",
        "surface-container-low": "#f4f3f7",
        "on-surface-variant": "#43474e",
        "on-error-container": "#93000a",
        "tertiary": "#112235",
        "on-primary-fixed-variant": "#2d476f",
        "surface-bright": "#faf9fd",
        "secondary-fixed": "#e0e3e5",
        "on-surface": "#1a1c1e",
        "surface-container-highest": "#e3e2e6",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c6cf",
        "on-primary": "#ffffff",
        "primary": "#002045",
        "background": "#faf9fd",
        "surface-container": "#efedf1",
        "on-tertiary-container": "#90a0b9",
        "error": "#ba1a1a",
        "outline": "#74777f",
        "on-secondary-fixed": "#191c1e",
        "surface-container-high": "#e9e7eb",
        "primary-fixed": "#d6e3ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack_sm": "8px",
        "margin_page": "40px",
        "stack_md": "16px",
        "gutter": "24px",
        "sidebar_width": "280px",
        "stack_lg": "32px",
        "container_max_width": "1440px"
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
